[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "dd1b05af7210cf0137a416db459dbade85867c74"
os = "macos"

    [[iso_codes.download]]
    sha256 = "62aa17ab82e4429669507cb5d1f70a84f110eea6b2b641f5bdc1b28ca900e75b"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.x86_64-apple-darwin14.tar.gz"
[[iso_codes]]
arch = "i686"
git-tree-sha1 = "c5cc65643b676e89faefa84bff5db40770049dd3"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "6497fa0511dd7b69c853124db8f0112e0f77e8276bf28acc476c2c99595bf0e6"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.i686-linux-gnu.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "b24cd6af59a7366414e6f10309b8a246ce907930"
os = "freebsd"

    [[iso_codes.download]]
    sha256 = "d8b74db1acb38add77f75e18f532192ef331053923c2c8cd512bc639652eb35c"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.x86_64-unknown-freebsd11.1.tar.gz"
[[iso_codes]]
arch = "powerpc64le"
git-tree-sha1 = "ef6d39dbc9db8268bd4744ee04ffcf41a31a9d18"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "924d30009e5b1f234d110144d03daa45386b3dbea7b90b39abf65c097916a5ea"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.powerpc64le-linux-gnu.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "93f322d0e39c4f391a5f4fb877f94b3dd34338a7"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "951fa596cd5c7c0c954952baac779b5f125a8005dd1bafb4a71a5fcff3cd5f6f"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.x86_64-linux-musl.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "a7c70e6c8df86e725ae8667433ec3111cd45da59"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "4ba7d1ebe4b10b411382b3c808cf52865c3f3800cd2306b2f42f2127ed64b4ad"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.x86_64-linux-gnu.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "43666dabd9c384faf5620234a3406c901777e948"
os = "windows"

    [[iso_codes.download]]
    sha256 = "982785811ebb7efa10c02a03ef7388d4540e4d183dbc9cf64621cfa8759d0a47"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.x86_64-w64-mingw32.tar.gz"
[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "6238fdeb9d27c52b7aef6dcfb240839a7dc5c176"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "1e5779cc90a9a87671d67731f7d63822e0f30ee065de5920aeba0bdaf99a4924"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.aarch64-linux-musl.tar.gz"
[[iso_codes]]
arch = "armv7l"
git-tree-sha1 = "8aa7ed50c77c134416e8d9927c4cbe0f1a27d59b"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "36166c53cf8df8d611c36fbbccf87ca912111152517f460d1a07c07ed9cd0fd6"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.arm-linux-gnueabihf.tar.gz"
[[iso_codes]]
arch = "i686"
git-tree-sha1 = "2bd46d94532060aadae4a46036a266ba11b2476f"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ae1f0587f084d9702a0a4709d483467a59ceb44113899cf1330d2e368c85a703"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.i686-linux-musl.tar.gz"
[[iso_codes]]
arch = "armv7l"
git-tree-sha1 = "ebba266df0cffb490e0b22bf7050bda92268a78a"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "b9af060e9bd34790815dc7fc5bb1b5bad535fbd0f135467e554b1d9d7ff21b1b"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.arm-linux-musleabihf.tar.gz"
[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "c6dc2825bba865dd69fc81c7d6e15350513779bd"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "8085bf2c6ba81e8e6b4c276b0f713405a56ef88ce642dc68fbc804457177f16d"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.aarch64-linux-gnu.tar.gz"
[[iso_codes]]
arch = "i686"
git-tree-sha1 = "078e83735e09945ca3817187febfecc63805b91a"
os = "windows"

    [[iso_codes.download]]
    sha256 = "f46e05a292dec564251d003ab8a190ef374937e14e14709fb8387305aac027b2"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.3.0+1/iso_codes.v4.3.0.i686-w64-mingw32.tar.gz"
